# Funding links (optional - shows "Sponsor" button on repo)
# Uncomment and fill in the platforms you use

# github: yourusername
# patreon: yourusername
# ko_fi: yourusername
# buy_me_a_coffee: yourusername
# custom: ["https://your-donation-link.com"]

